extends: substitution
message: "Используйте '%s' вместо '%s'."
level: warning
ignorecase: true

swap:
  "осуществить создание": "создать"
  "осуществить настройку": "настроить"
  "осуществлять проверку": "проверять"
  "произвести настройку": "настроить"
  "произвести выбор": "выбрать"
  "произвести установку": "установить"
  "в целях": "чтобы"
  "в рамках": "в"
  "данный": "этот"
  "вышеуказанный": "указанный"
  "вышеизложенный": "указанный"
  "посредством": "с помощью"
  "при помощи": "с помощью"
  "является": ""
  "необходимо выполнить": "выполните"
  "необходимо осуществить": "выполните"
  "осуществить переход": "перейдите"
  "произвести нажатие": "нажмите"
  "нажать на кнопку": "нажмите кнопку"
